api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from api import views

from api.views import ContactViewSet, MailingViewSet, MessageViewSet

app_name = 'api'

router_v1 = DefaultRouter()
router_v1.register('contacts', ContactViewSet)
router_v1.register('mailings', MailingViewSet)
router_v1.register('messages', MessageViewSet)

urlpatterns = [
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router_v1.urls)),
    path('', views.APIRootView.as_view(), name='root'),
    # path('', include(('router_v1.urls', 'api'), namespace='api')),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from api.views import index

schema_view = get_schema_view(
    openapi.Info(
        title="Сервис уведомлений API",
        default_version='v1',
        description="Документация",
        contact=openapi.Contact(email="abdullasalimov7@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
]

urlpatterns += [
    re_path(r'^docs(?P<format>\.json|\.yaml)$',
        schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^docs/$', schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'),
]

mailings/models.py
from django.db import models
from django.core.validators import RegexValidator


class Contact(models.Model):
    phone_regex = RegexValidator(regex=r'^7\d{10}$', message="Номер телефона необходимо вводить в формате: '7XXXXXXXXX'. разрешено только 11 цифр. (X - цифра от 0 до 9)")
    number = models.CharField(validators=[phone_regex], max_length=11, unique=True, blank=False)
    code = models.CharField(max_length=10)
    tag = models.CharField(null=True, blank=False, max_length=50)
    time_zone = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.number}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

class Mailing(models.Model):
    start_send_time = models.DateTimeField()
    text = models.TextField()
    tag = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    end_send_time = models.DateTimeField()

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

class Message(models.Model):
    STATUS_CHOICES = (
        ('S', 'send'),
        ('N', 'not send'),
    )
    send_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        related_name='messages'
    )
    contact = models.ForeignKey(
        Contact,
        on_delete=models.CASCADE,
        related_name='messages'
    )

    def __str__(self):
        return f'{self.mailing} {self.contact} {self.status}'
    
    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

api/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework import generics

from mailings.models import Contact, Mailing, Message

from .serializers import (ContactSerializer, MailinglistSerializer,
                          MailingSerializer, MessageSerializer)

from rest_framework.response import Response

from django.shortcuts import render
from django.urls import reverse

class APIRootView(generics.GenericAPIView):
    def list(self, request):
        return Response({
            'contacts': reverse('contact-list', request=request),
            'mailings': reverse('mailing-list', request=request),
            'messages': reverse('message-list', request=request),
        })


class ContactViewSet(viewsets.ModelViewSet):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = ('tag', 'code')


class MailingViewSet(viewsets.ModelViewSet):
    queryset = Mailing.objects.all()
    serializer_class = MailingSerializer

    def get_serializer_class(self):
        if self.action == 'list':
            return MailinglistSerializer
        return MailingSerializer


class MessageViewSet(viewsets.ModelViewSet):
    queryset = Message.objects.all()
    serializer_class = MessageSerializer


def index(request):
    return render(request, 'index.html')

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис уведомлений</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>

<body>
    <div class="container px-4 py-5" id="hanging-icons">
        <h2 class="pb-2 border-bottom">Сервис уведомлений</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-4">
            <div class="col d-flex align-items-start">
                <div>
                    <h2>API</h2>
                    <a href="{% url 'api:root' %}" class="btn btn-primary">
                        Войти
                    </a>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div>
                    <h2>Admin</h2>
                    <a href="{% url 'admin:index' %}" class="btn btn-primary">
                        Войти
                    </a>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div>
                    <h2>Docs</h2>
                    <a href="{% url 'schema-swagger-ui' %}" class="btn btn-primary">
                        Войти
                    </a>
                </div>
            </div>
            <div class="col d-flex align-items-start">
                <div>
                    <h2>Redoc</h2>
                    <a href="{% url 'schema-redoc' %}" class="btn btn-primary">
                        Войти
                    </a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
    </script>
</body>

</html>